### ISSUE TITLE
Multi tenancy failed (missing functions in module identity)

### ISSUE THREAD

**Issue by giarbi** [Azure/AzureStack-Tools#261]
Register-GuestDirectoryTenantToAzureStack
Register-AzureStackWithMyDirectoryTenant

![2017-07-13 09_21_52-administrator_ windows powershell ise](https://user-images.githubusercontent.com/13151763/28155458-22df4284-67af-11e7-88df-2828b997e885.png)

**Comment by RuudBorst** [comment]
Also see https://social.msdn.microsoft.com/Forums/azure/en-US/4ac8b7b9-7872-4e87-9147-18aa5f8318a8/enable-multitenancy-in-azure-stack-failed-in-asdk?forum=AzureStack

**Comment by troettinger** [comment]
should be fixed, give it a try and let me know

**Comment by giarbi** [comment]
Still not working

PS C:\AzureStack-Tools-master> $adminARMEndpoint = "https://adminmanagement.local.azurestack.external"
$azureStackDirectoryTenant = "gia365.onmicrosoft.com" # this is the primary tenant Azure Stack is registered to
$guestDirectoryTenantToBeOnboarded = "giad.onmicrosoft.com" # this is the new tenant that needs to be onboarded to Azure Stack
$location = "local"
Register-AzsGuestDirectoryTenant -AdminResourceManagerEndpoint $adminARMEndpoint `
    -DirectoryTenantName $azureStackDirectoryTenant `
    -GuestDirectoryTenantName $guestDirectoryTenantToBeOnboarded `
    -Location $location
Register-AzsGuestDirectoryTenant : The term 'Register-AzsGuestDirectoryTenant' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
At line:5 char:1
+ Register-AzsGuestDirectoryTenant -AdminResourceManagerEndpoint $admin ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Register-AzsGuestDirectoryTenant:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Kind Regards
Robert

Von: Thomas Roettinger [mailto:notifications@github.com]
Gesendet: Samstag, 15. Juli 2017 00:49
An: Azure/AzureStack-Tools <AzureStack-Tools@noreply.github.com>
Cc: Bienz Robert (GIARBI) <Robert.Bienz@gia.ch>; Author <author@noreply.github.com>
Betreff: Re: [Azure/AzureStack-Tools] Multi tenancy failed (missing functions in module identity) (#261)


should be fixed, give it a try and let me know

**Comment by giarbi** [comment]
There is another issue in the function, Resourcegroup system not found

PS C:\AzureStack-Tools-master> $adminARMEndpoint = "https://adminmanagement.local.azurestack.external"
$azureStackDirectoryTenant = "gia365.onmicrosoft.com" # this is the primary tenant Azure Stack is registered to
$guestDirectoryTenantToBeOnboarded = "giad.onmicrosoft.com" # this is the new tenant that needs to be onboarded to Azure Stack
$location = "local"
Register-AzsGuestDirectoryTenant -AdminResourceManagerEndpoint $adminARMEndpoint `
    -DirectoryTenantName $azureStackDirectoryTenant `
    -GuestDirectoryTenantName $guestDirectoryTenantToBeOnboarded `
    -Location $location
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AS.Impersonation\Impersonation.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AS.Impersonation\Impersonation.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AS.Impersonation\Impersonation.psm1'.
VERBOSE: GET https://adminmanagement.local.azurestack.external/metadata/endpoints?api-version=2015-01-01 with 0-byte payload
VERBOSE: received 349-byte response of content type application/json; charset=utf-8
VERBOSE: Endpoints: {
    "galleryEndpoint":  "https://adminportal.local.azurestack.external:30015/",
    "graphEndpoint":  "https://graph.windows.net/",
    "portalEndpoint":  "https://adminportal.local.azurestack.external/",
    "authentication":  {
                           "loginEndpoint":  "https://login.windows.net/",
                           "audiences":  [
                                             "https://adminmanagement.gia365.onmicrosoft.com/cf1b48d1-9d89-4ac0-9ec2-472fac90d014"
                                         ]
                       }
}
VERBOSE: GET https://login.windows.net/gia365.onmicrosoft.com/.well-known/openid-configuration with 0-byte payload
VERBOSE: received 1389-byte response of content type application/json; charset=utf-8
VERBOSE: GET https://login.windows.net/giad.onmicrosoft.com/.well-known/openid-configuration with 0-byte payload
VERBOSE: received 1389-byte response of content type application/json; charset=utf-8
VERBOSE: Performing the operation "Creating the resource..." on target "/subscriptions/529b0411-cb96-4cf4-a4bc-4d074c68221a/resourceGroups/system/providers/Microsoft.Subscriptions.Admin/directoryTenants/giad.onmicrosoft.com".
New-AzureRmResource : ResourceGroupNotFound : Resource group 'system' could not be found.
At line:67 char:28
+ ... oryTenant = New-AzureRmResource @params -Force -Verbose -ErrorAction  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : ResourceGroupNotFound,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceCmdlet





Kind Regards
Robert

Von: Thomas Roettinger [mailto:notifications@github.com]
Gesendet: Samstag, 15. Juli 2017 00:49
An: Azure/AzureStack-Tools <AzureStack-Tools@noreply.github.com>
Cc: Bienz Robert (GIARBI) <Robert.Bienz@gia.ch>; Author <author@noreply.github.com>
Betreff: Re: [Azure/AzureStack-Tools] Multi tenancy failed (missing functions in module identity) (#261)


should be fixed, give it a try and let me know

**Comment by troettinger** [comment]
I just did another update regarding the issue you have been reporting. Can you download the tools from the **vnext branch** and validate? And report back

**Comment by giarbi** [comment]
Register-AzsGuestDirectoryTenant is now ok but next step Register-AzsWithMyDirectoryTenant failes.


[cid:image001.png@01D30058.257FC950]

Kind Regards
Robert

Von: Thomas Roettinger [mailto:notifications@github.com]
Gesendet: Montag, 17. Juli 2017 19:00
An: Azure/AzureStack-Tools <AzureStack-Tools@noreply.github.com>
Cc: Bienz Robert (GIARBI) <Robert.Bienz@gia.ch>; Author <author@noreply.github.com>
Betreff: [SPAM] Re: [Azure/AzureStack-Tools] Multi tenancy failed (missing functions in module identity) (#261)
Priorität: Niedrig


I just did another update regarding the issue you have been reporting. Can you download the tools from the vnext branch and validate? And report back

**Comment by RedBa** [comment]
There was another issue in the script. Did a pull-request. But even after all these updates the mulit-tanancy does not works. The part of singing up the guest AAD via the URL seems to not work. https://portal.local.azurestack.external/guest/signup/< guestDirectoryName >

**Comment by wmrichard** [comment]
It looks like it has been fixed. I used the steps described on: https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-enable-multitenancy .
